export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}) {
  return (
    <html lang="en">
      <body className={typeof window !== 'undefined' ? 'default-body-class' : ''}>{children}</body>
    </html>
  )
}
