import  SideNav  from "../(components)/SideNav";
import  TopNav  from "../(components)/TopNav";

export const metadata = {
    title: 'Mentor',
    description: 'Generated by Next.js',
  }
  
  export default function MentorLayout({children}) {
    return (
        <div>
          <TopNav/>
          <SideNav/>
          {children}</div>
    )
  }
  