import TopNav from "../(components)/TopNav";
import SideNav from "../(components)/SideNav";


export const metadata = {
  title: 'Login',
  description: 'Generated by Next.js',
}

export default function LoginLayout({
  children,
}) {
  return (
      <div className="font-sans" suppressHydrationWarning={true}>{children}</div>
  )
}
