
export const metadata = {
  title: "Landing Page",
  description: "Generated by create next app",
};

export default function LandingPageLayout({ children }) {
  return (
    <>
      <div className="antialiased poppins_e0ec69b1-module__5uaDPG__variable poppins_e0ec69b1-module__5uaDPG__">
        {children}
      </div>
    </>
  );
}
