
import "../globals.css";





export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="antialiased poppins_e0ec69b1-module__5uaDPG__variable poppins_e0ec69b1-module__5uaDPG__">
      {children}
      </body>
    </html>
  );
}
